### ISSUE TITLE
Need a hex logo!

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack-hq#1]
And perhaps some stickers too?

**Comment by annakrystalli** [comment]
A potential start!

![reprohack](https://user-images.githubusercontent.com/5583057/59551734-143d8600-8f76-11e9-8bec-fd947cf4744f.png)

**Comment by annakrystalli** [comment]
Thoughts welcome @flor14 :)

**Comment by flor14** [comment]
Sounds great! It first came to my mind:
https://en.wikipedia.org/wiki/Recycling#/media/File:Recycling_symbol.svg
 , but reproducibility it is not really about "recycling". Anyway, I like
the circle or circling idea. You obtain at the end the same what you start
with.
It would be nice also that the logo should also represent sharing with
others.

Let's the brainstorming continue...

**Comment by annakrystalli** [comment]
Oooh yes, I agree about somehow including the aspect of sharing (ie that reproducibility has a social/communication aspect at its core) into the logo. Re the recycling, I agree that I feel it's not quite the right symbol which is why I opted more for "repeat" symbol.

Looking forward to discussing later!

**Comment by annakrystalli** [comment]
Inspiration from workflowr
![image](https://user-images.githubusercontent.com/5583057/60724085-677b7680-9f2d-11e9-846b-855a4363df8d.png)

But I suggest a teal color and a simple white graphic

**Comment by annakrystalli** [comment]
Refining the idea down to:
- keep the recycling icon
- keep the checkmark
- include the people aspect (sharing / learning)

**Comment by flor14** [comment]
In Canva there are these kinds of logos (but are paid). For inspiration only
![image](https://user-images.githubusercontent.com/29610858/60757246-930a6980-9fde-11e9-9805-6368d46c603b.png)

**Comment by flor14** [comment]
Another possibility could include a simplification of the actual logo inside the overlapping part of the vignettes in this image
![image](https://user-images.githubusercontent.com/29610858/60757265-cd740680-9fde-11e9-875b-2f376ef73930.png)

**Comment by annakrystalli** [comment]
OK, I had another go incorporating some of these ideas.

What do you think @flor14 ?

![reprohack](https://user-images.githubusercontent.com/5583057/61451345-0aca8380-a951-11e9-8eaa-21c1866fe8b1.png)
