### ISSUE TITLE
Select Hugo theme

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack-hq#15]
https://themes.gohugo.io/

**Comment by annakrystalli** [comment]
## Anna's choices

- [Kross](https://themes.gohugo.io/kross-hugo-portfolio-template/)
    ![](https://d33wubrfki0l68.cloudfront.net/018b81258bf85978e25d81df3f588a5b6d696fdb/33d27/kross-hugo-portfolio-template/screenshot-kross-hugo-portfolio-template_hua1726dc50382dc8979d1f90fa43be446_229423_1500x1000_fill_catmullrom_top_2.png)
- [Meghna Hugo](https://themes.gohugo.io/meghna-hugo/)
    ![](https://d33wubrfki0l68.cloudfront.net/7471fbc7963e544eefce7089c012571f6e7d3423/f35a0/meghna-hugo/screenshot-meghna-hugo_hua08ed15aee9bdb7eb6d182ddeac95548_789341_1500x1000_fill_catmullrom_top_2.png)
- [](https://themes.gohugo.io//theme/timer-hugo/post/)
    ![](https://d33wubrfki0l68.cloudfront.net/c92b41b3298ed64c82210e08d7ea77d0aa2d0a3f/da757/timer-hugo/screenshot-timer-hugo_hub2f78306d88765c58757d0b657f00e40_481046_1500x1000_fill_catmullrom_top_2.png)

**Comment by flor14** [comment]
I have been playing with this, but I found that there is a difference between Magna template and the other two. Magna template is organized as the webpage of a company and the other 2 as personal blogs. Not sure which kind of template fits better our purposes. Maybe the company one.

Not sure if you were aware of this difference.

![image](https://user-images.githubusercontent.com/29610858/66341807-5d975400-e91e-11e9-8751-7703b9e7554a.png)

**Comment by annakrystalli** [comment]
Not needed anymore. Custom site to be built using django.
