### ISSUE TITLE
Specialised Code of Conduct

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack-hq#3]
We need a custom code of conduct appropriate to events with a custom section for interactions with authors:
- Inspiration from [Carpentries](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html) / [R Consortium](https://wiki.r-consortium.org/view/R_Consortium_and_the_R_Community_Code_of_Conduct) 
- Specific about communications on social media
- **VERY IMPORTANT: A section about how to feedback to authors**
    - Acknowledge and thank them for their efforts
    - Constructive criticism only

**Comment by orchid00** [comment]
for inspiration https://github.com/galaxyproject/training-material/blob/master/CODE_OF_CONDUCT.md

**Comment by annakrystalli** [comment]
Great suggestion @orchid00 ! I've also updated the original comment with more details/context which were on the meeting minutes :)

**Comment by annakrystalli** [comment]
Closing as dealt with in #25 

Thanks again @orchid00 for the suggestion. In the end we did mainly adapt the Galaxy CoC.
